project_name: dynatrace-kube-hunter-ingester
before:
  hooks:
    - go mod tidy
builds:
  - id: app
    binary: app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -v
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
dockers:
  - id: app
    goos: linux
    image_templates:
      - "martinnirtl/dynatrace-kube-hunter-ingester:latest"
      - "martinnirtl/dynatrace-kube-hunter-ingester:{{ .Tag }}"
    use: buildx
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
