project_name: dynatrace-kube-hunter-ingester

before:
  hooks:
    - go mod tidy

builds:
  - id: app
    binary: app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -v
    ldflags:
    - -X cmd.version={{ .Version }}
    - -X cmd.commit={{ .Commit }}
    - -X cmd.date={{ .CommitDate }} 
    - -X main.builtBy=goreleaser

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

dockers:
  - image_templates:
      - "martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
    goarch: amd64
  - image_templates:
      - "martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
    goarch: arm64

docker_manifests:
- name_template: 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}'
  image_templates:
  - 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-amd64'
  - 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-arm64'
- name_template: 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Major }}{{ .Minor }}'
  image_templates:
  - 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-amd64'
  - 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-arm64'
- name_template: 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Major }}'
  image_templates:
  - 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-amd64'
  - 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-arm64'
- name_template: 'martinnirtl/dynatrace-kube-hunter-ingester:latest'
  image_templates:
  - 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-amd64'
  - 'martinnirtl/dynatrace-kube-hunter-ingester:{{ .Version }}-arm64'

changelog:
  sort: asc
  filters:
    exclude:
      - "^dev:"
      - "^docs:"
      - "^test:"
