apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-kube-hunter-ingester
  labels:
    app: dynatrace-kube-hunter-ingester
spec:
  selector:
    matchLabels:
      app: dynatrace-kube-hunter-ingester
  template:
    metadata:
      labels:
        app: dynatrace-kube-hunter-ingester
    spec:
      containers:
      - name: dynatrace-kube-hunter-ingester
        image: martinnirtl/dynatrace-kube-hunter-ingester
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}